apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wnyss3d44-nodejs 
  janus-idp.io/tekton: wnyss3d44-nodejs
  backstage.io/kubernetes-id: wnyss3d44-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wnyss3d44-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml