apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wnyss3d44-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wnyss3d44-nodejs 
  name: wnyss3d44-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wnyss3d44-nodejs 
